In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.2'

In [3]:
print(npdoc)

NameError: name 'npdoc' is not defined

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [5]:
l=[1,2,3,4,5]

In [11]:
array=np.array(l)

In [12]:
type(np.array(l))

numpy.ndarray

In [13]:
array.ndim

1

In [21]:
l=[1,2,3,4,5,6,"shahanshah"]

In [26]:
l

[1, 2, 3, 4, 5, 6, 'shahanshah']

In [28]:
arr1=np.array(l)

In [29]:
arr1

array(['1', '2', '3', '4', '5', '6', 'shahanshah'], dtype='<U21')

In [30]:
array.ndim

1

In [32]:
arr1=np.array([[1,2,3],[4,5,6]])

In [33]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr1.ndim

2

In [37]:
l=[1,2,3,4,]

In [39]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [40]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [41]:
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [44]:
# more way to connvert to array

np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [56]:
np.asarray ([[[1,2],[3,4],[5,6]]]) #Convert the input to an array.

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [57]:
mat

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [55]:
array = np.asanyarray(mat)

In [58]:
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [59]:
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [61]:
t=([1,2,3],[5,6,7])
type(t)

tuple

In [62]:
np.array(t)

array([[1, 2, 3],
       [5, 6, 7]])

In [63]:
a=5
np.array(a)

array(5)

In [64]:
L=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4])

In [65]:
arr[2]

3

In [66]:
arr[0]=100

In [67]:
arr

array([100,   2,   3,   4])

5

 # to create array >>>.array.asarray,deepcopy,shallcopy

In [73]:
np.fromfunction(lambda i,j :i==j, shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [74]:
array

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [79]:
arr.shape

(4,)

In [80]:
arr1.shape

(2, 3)

In [83]:
array.shape

(1, 3, 2)

In [83]:
array.shape

(1, 3, 2)

In [86]:
array.size

6

In [85]:
arr.size

4

In [84]:
arr1.shape

(2, 3)

In [88]:
arr.size

4

In [92]:
np.fromfunction(lambda i,j :i==j, shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [93]:
np.fromfunction(lambda i,j :i*j, shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [95]:
range(5)

range(0, 5)

In [105]:
for i in range(5):
    print(i)

0
1
2
3
4


In [108]:
[ i for i in range(5)]

[0, 1, 2, 3, 4]

In [110]:
list(i for i in range (5))

[0, 1, 2, 3, 4]

In [115]:
iterable=(i*i  for i in range (5))

In [127]:
np.fromiter(iterable,float )

array([], dtype=float64)

In [128]:
np.fromstring("12 34 56",sep = " ")

array([12., 34., 56.])

In [131]:
np.fromstring("12 ,34, 56",sep = " ,")

array([12., 34., 56.])

In [122]:
np.fromstring("shahanshah, mohammad,kashibari",sep=" ,")

/var/folders/lh/dzt8v5p97d16vhdw9qhp8cfr0000gn/T/ipykernel_6677/2353442347.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("shahanshah, mohammad,kashibari",sep=" ,")


array([], dtype=float64)

In [132]:
arr.dtype

dtype('int64')

In [133]:
l=[1,2,3]
arr=np.array(l)
arr.dtype

dtype('int64')

In [134]:
l=[1,2,3,"shahanshah"]
arr=np.array(l)
arr.dtype

dtype('<U21')

In [135]:
list(range(5))

[0, 1, 2, 3, 4]

In [136]:
range(5)

range(0, 5)

In [145]:
np.arange(0.1, 10.2, 0.1)

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1])

In [153]:
list(np.arange(0.1, 10.2, 0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [154]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [157]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [161]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [166]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [167]:
arr3=np.zeros((3,3,4))
arr3.shape

(3, 3, 4)

In [168]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [169]:
arr3.ndim

3

In [171]:
arr4=np.zeros((4,3,4))
arr4.shape

(4, 3, 4)

In [172]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [173]:
arr4.ndim

3

# END CLASS  